### ISSUE TITLE
Issue using Api in Android

### ISSUE THREAD

**Issue by kashifiqbal112** [square/connect-java-sdk#19] opened 2017-07-24 23:55 UTC
i add sqaure point of sale api in android from this
compile 'com.squareup:connect:2.2.0' and use Retrolamda with Java 8 butt i got this error on run .

com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: javax/inject/Inject.class

**Comment by ellapolo** [comment] 2017-08-01 22:11
Hello,
-  I see you wrote you want to add Square Point of Sale API, but you put the compile statement for the Connect SDK. The latter makes more sense here, but if you want to import the POS API instead you would use   compile 'com.squareup.sdk:point-of-sale-sdk:2.0'
- Are you using Android Gradle Plugin version 3.0? If so you shouldn't need to use Retrolambda
- Are you depending on Dagger or another library that depends on Inject? If so you might try excluding the inject library from that dependency.

**Comment by ekrusznis** [comment] 2018-07-09 13:21
Hello,
Not sure if its still an issue but the duplicate entry issue can be resolved by adding this to your gradle-
implementation ('com.squareup:connect:2.9.0'){
        exclude module: 'javax.inject'
    }

Now...after LOTS of debugging and multiple errors that I have googled and figured out..
_Fatal signal 11 (SIGSEGV), code 2, fault addr 0x76674409c0 in tid 28434 (com.ek.pos), pid 28434 (com.ek.pos)_

This is my error, there is no other logs and no other issues. It crashes the app at startup. Any idea?

**Comment by ekrusznis** [comment] 2018-07-09 15:40
I finally resolved this, I believe I was able to by updating my Minimum version to 26.
Now, next error. below.
It is pointing to my try/catch, specfiically the 'List<Locations> line.

        try {
           List<Location> locations = locationsApi.listLocations().getLocations();
            System.out.println(locations);
        } catch (ApiException e) {
            System.err.println("Exception when calling API");
            e.printStackTrace();
        }- 



07-09 11:28:04.498 24112-24112/com.ek.pos E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ek.pos, PID: 24112
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ek.pos/com.ek.pos.MainActivity}: javax.ws.rs.ProcessingException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: javax.ws.rs.ProcessingException
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:264)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
        at com.squareup.connect.ApiClient.invokeAPI(ApiClient.java:673)
        at com.squareup.connect.api.LocationsApi.listLocations(LocationsApi.java:71)
        at com.ek.pos.MainActivity.onCreate(MainActivity.java:39)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1450)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:102)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
        at java.net.InetAddress.getAllByName(InetAddress.java:787)
        at com.android.okhttp.Dns$1.lookup(Dns.java:39)
        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
        at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(Unknown Source:0)
        at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:394)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
        	... 25 more
07-09 11:28:04.522 24112-24112/com.ek.pos I/Process: Sending signal. PID: 24112 SIG: 9

**Closed** 2019-08-13 20:55 UTC
